name: CI Checks

on:
  # trigger for all PR events
  pull_request:
  # make this workflow able to be called by other workflows
  workflow_call:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: |
          echo "npm install"
          sleep 5

      - name: Build
        run: |
          echo "npm run build"
          sleep 8

      - name: Lint
        run: |
          echo "npm run lint"
          sleep 5

      - name: Tests
        run: |
          echo "npm test"
          sleep 8
