name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - run: |
          echo "npm install"
          sleep 15

      - name: Build
        run: |
          echo "npm run build"
          sleep 10

      - name: Lint
        run: |
          echo "npm run lint"
          sleep 10

      - name: Run Tests
        run: |
          echo "npm test"
          sleep 12
