name: Deploy Job
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: 'The target environment for deployment'
        default: 'dev'

jobs:
  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ inputs.environment }}.example.com"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deployment
        run: |
          echo "Deploying to ${{ inputs.environment }} Environment"
          sleep 30
          # Deployment steps...
          echo "done"

      - name: Smoke Tests
        run: |
          echo "Running Smoke Tests for ${{ inputs.environment }} Environment"
          sleep 10
          echo "done"
