name: Deploy to Development

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [dev]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: dev
      url: https://dev.example.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to Dev Environment"
          sleep 30
          # Deployment steps...
          echo "done"
